version: "3"

networks:
  bridge:
    driver: bridge

services:
  flink-processor:
    build:
      context: ./flink-processor
    container_name: flink-processor
    # image: flink-processor
    # depends_on:
    #   - kafka
    environment:
      KAFKA_SERVER: "kafka:9092"
      ZOOKEEPER_SERVER: "zookeeper:32181"
      PRODUCER_INTERVAL: 100
    networks:
      - bridge

volumes:
  settings:
  data:
