version: "3.9"

networks:
  bridge:
    driver: bridge

services:
  flink-processor:
    build:
      context: ./flink-processor
    container_name: flink-processor
    # image: flink-processor
    # depends_on:
    #   - kafka
    environment:
      KAFKA_SERVER: "kafka:9092"
      ZOOKEEPER_SERVER: "zookeeper:32181"
      PRODUCER_INTERVAL: 100
    networks:
      - bridge

  postgres:
    build:
      context: ./postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5438:5432
    networks:
      - bridge

volumes:
  settings:
  data:
